### ISSUE TITLE
Connect contacts

### ISSUE THREAD

**Issue by anno73** [elias0172/Battery-PSU-HW#1]
Hi!

Interesting concept! Would you mind adding a photo of the inside where one can see the faston connectors connecting to the wires please?

Thanx a lot!

**Comment by elias0172** [comment]
> Hi!
> 
> Interesting concept! Would you mind adding a photo of the inside where one can see the faston connectors connecting to the wires please?
> 
> Thanx a lot!

Hi, thank you!
Unfortunately I covered the faston connectors with hot glue, nevertheless I opened pandora's box and took some photos. I just soldered wires to the pins which goes normally through the pcb.
![pctdetail.834-009.1.jpg](https://user-images.githubusercontent.com/84908851/148641652-a6b25fce-b1b9-4bb6-bb8c-c2b0c1c7cdd6.jpg)

![20220107_215318.jpg](https://user-images.githubusercontent.com/84908851/148641678-82e9d5ab-5103-4345-bc1b-32f9a091a89a.jpg)
